config/routes.rb
Rails.application.routes.draw do
  resources :elves
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/elf.rb
class Elf < ApplicationRecord
  #== Constants ================================================================
  #== Attributes ===============================================================
  #== Extensions ===============================================================
  #== Relationships ============================================================
  #== Validations ==============================================================
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :speciality
  #== Scopes ===================================================================
  #== Callbacks ================================================================
  #== Class Methods ============================================================
  #== Instance Methods =========================================================
end

app/controllers/application_controller.rb
require 'application_responder'

class ApplicationController < ActionController::Base
  include LogragePayload
  include ActiveModelSerializerPagination

  self.responder = ApplicationResponder
  respond_to :html
end

app/controllers/concerns/active_model_serializer_pagination.rb
module ActiveModelSerializerPagination
  extend ActiveSupport::Concern

  def pagination_meta(object)
    {
      current_page: object.current_page,
      next_page:    object.next_page,
      prev_page:    object.prev_page,
      total_pages:  object.total_pages,
      total_count:  object.total_count
    }
  end
end

app/controllers/concerns/lograge_payload.rb
module LogragePayload
  extend ActiveSupport::Concern

  def append_info_to_payload(payload)
    super
    payload[:request_id] = request.uuid
    payload[:user_id] = current_user.id if try(:current_user)
  end
end

app/controllers/elves_controller.rb
class ElvesController < ApplicationController
  respond_to :html

  def index
    @q = Elf.all.search params[:q]
    @elves = @q.result.page(params[:page])

    respond_with @elves, meta: pagination_meta(@elves)
  end

  def show
    @elf = Elf.find params[:id]
    respond_with @elf
  end

  def new
    @elf = Elf.new
  end

  def edit
    @elf = Elf.find params[:id]
    respond_with @elf
  end

  def create
    @elf = Elf.new(elf_params)
    @elf.save
    respond_with @elf
  end

  def update
    @elf = Elf.find params[:id]
    @elf.update(elf_params)
    respond_with @elf
  end

  def destroy
    @elf = Elf.find params[:id]
    @elf.destroy
    respond_with @elf
  end

  private

  def elf_params
    params.require(:elf).permit(
      :first_name,
      :last_name,
      :date_of_birth,
      :speciality
    )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  respond_to :html
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # override default kaminari pagination method to use twitter-bootstrap theme
  def paginate(objects, options={})
    options.reverse_merge!(theme: 'twitter-bootstrap-4',
                           pagination_class: 'pagination-sm')
    super(objects, options)
  end
end

app/views/elves/_form.html.haml
= bootstrap_form_for @elf, layout: :vertical do |f|
  .container
    = f.text_field :first_name
    = f.text_field :last_name
    = f.text_field :speciality
    = f.date_field :date_of_birth

    = f.primary

app/views/elves/edit.html.haml
= render 'form'

app/views/elves/index.html.haml
.row
  .col.d-flex.align-items-center.justify-content-between
    %h1= "#{@elves.count} #{Elf.model_name.human(count: @elves.count)}"
    = link_to t('actions.create'), new_elf_path, class: 'btn btn-primary'

%table.table
  %thead
    %tr
      %th= sort_link(@q, :first_name, Elf.human_attribute_name(:name))
      %th= sort_link(@q, :speciality, Elf.human_attribute_name(:speciality))
      %th= sort_link(@q, :created_at, Elf.human_attribute_name(:created_at))
      %th{colspan: 3}

  %tbody
    - @elves.each do |elf|
      %tr
        %td= elf.full_name
        %td= elf.speciality
        %td= elf.created_at.strftime('%e %B %Y')

        %td.actions
          = link_to t('actions.edit'), edit_elf_path(elf), class: 'btn btn-xs btn-light'
          = link_to t('actions.delete'), elf_path(elf), { method: :delete, class: 'btn btn-xs btn-warning', data: { confirm: t('actions.delete_question')}}

.pull-right
  = paginate @elves

app/views/elves/new.html.haml
= render 'form'

app/views/home/index.html.haml
%h1
  Merry Christmas! 🎅

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Sping Admin
    /
      admin
      version: #{Rails.application.config.version} (#{l(Rails.application.config.version_time)})
    = action_cable_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    /[if lt IE 9]
      %script{src: "//cdnjs.cloudflare.com/ajax/libs/es5-shim/2.0.8/es5-shim.min.js"}
      %script{src: "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"}
      %script{src: "//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.js"}
      %script{src: "//cdnjs.cloudflare.com/ajax/libs/json3/3.3.2/json3.min.js"}
    = csrf_meta_tags
  %body{class: "#{controller.controller_name} #{@full_height_page ? 'full-height' : nil}"}
    %nav.navbar.navbar-expand-lg.navbar-light.bg-light
      = link_to t('navbar.home'), root_path, class: 'navbar-brand'
      %button.navbar-toggler(data-target='#navbarNav' data-toggle='collapse' type='button')
        %span.navbar-toggler-icon

      .collapse.navbar-collapse
        %ul.navbar-nav.mr-auto
          %li.nav-item{class: "#{'active' if is_active_link?(elves_path)}"}
            = link_to Elf.model_name.human(count: 2), elves_path, class: 'nav-link'

    .main-content.container-fluid
      - flash.each do |type, msg|
        %div{class: "alert alert-#{type == 'alert' ? 'danger' : 'success'} alert-dismissable", role: 'alert'}
          %button.close{type: 'button', data: {dismiss: 'alert'}, aria: {label: 'Close'}}
            %span{aria: {hidden: 'true'}} &times;
          = msg if msg.is_a?(String)

      = yield

  = javascript_include_tag  'application'
  = javascript_pack_tag     'application'
  = yield :javascripts